apiVersion: v1
kind: Service
metadata:
  name: {{ include "php-fpm.fullname" . }}
  labels:
{{ include "php-fpm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "php-fpm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
