# Web
web:
  replicaCount: 1
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  image:
    name: nginx:1.11
    pullPolicy: Always

  imagePullSecrets: []
  nameOverride: "name"
  fullNameOverride: "name"
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: chart-example.kz
        paths:
          - path: /
            service: service-name
    tls:
      - secretName: chart-example-tls
        hosts:
          - chart-example.kz

  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 128Mi

  extraVolumeMounts: []

  extraVolumes: []

  nodeSelector: []

  tolerations: []

  affinity: {}


# CLI

cli:
  replicaCount: 1
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

  image:
    name: nginx:1.11
    pullPolicy: Always

  imagePullSecrets: []
  nameOverride: "name"
  fullnameOverride: "name"
  service:
    type: ClusterIP
    port: 9000
    targetPort: 9000

  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 128Mi

  extraVolumeMounts: []

  extraVolumes: []

  nodeSelector: []

  tolerations: []

  affinity: {}

env:
  open: [ ]
  secret: [ ]
